name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Amplify
        run: |
          AMPLIFY_APP_ID=$(aws cloudformation describe-stacks --stack-name TodoListStack --query "Stacks[0].Outputs[?OutputKey=='AmplifyAppId'].OutputValue" --output text)
          APPSYNC_GRAPHQL_ENDPOINT=$(aws cloudformation describe-stacks --stack-name TodoListStack --query "Stacks[0].Outputs[?OutputKey=='GraphQLUrl'].OutputValue" --output text)
          APPSYNC_API_KEY=$(aws cloudformation describe-stacks --stack-name TodoListStack --query "Stacks[0].Outputs[?OutputKey=='ApiKey'].OutputValue" --output text)

          # Check for existing jobs
          EXISTING_JOBS=$(aws amplify list-jobs --app-id $AMPLIFY_APP_ID --branch-name main --query 'jobSummaries[?status==`PENDING` || status==`RUNNING`]' --output text)

          if [ -z "$EXISTING_JOBS" ]; then
            echo "No pending or running jobs. Starting a new build."
            aws amplify start-job --app-id $AMPLIFY_APP_ID --branch-name main --job-type RELEASE \
              --environment-variables "{\"APPSYNC_GRAPHQL_ENDPOINT\":\"$APPSYNC_GRAPHQL_ENDPOINT\",\"APPSYNC_API_KEY\":\"$APPSYNC_API_KEY\"}"
          else
            echo "There are pending or running jobs. Skipping new build."
            echo "Existing jobs:"
            echo "$EXISTING_JOBS"
          fi
